# Generated by Django 5.1.7 on 2025-03-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_header', models.ImageField(upload_to='logos/')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
