# Generated by Django 5.1.7 on 2025-03-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_configuracao_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='logo_url',
        ),
    ]
