# Generated by Django 5.1.7 on 2025-03-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
