# Generated by Django 5.1.7 on 2025-03-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_agendamento_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='melhor_horario_contato',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='mensagem',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='titulo',
            field=models.CharField(default='Sem título', max_length=200),
        ),
    ]
