# Generated by Django 5.1.7 on 2025-03-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_bannercarrossel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercarrossel',
            name='imagem',
            field=models.ImageField(upload_to='banners/'),
        ),
    ]
