# Generated by Django 5.1.7 on 2025-03-25 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_bannercarrossel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercarrossel',
            name='imagem',
            field=models.FileField(upload_to='banners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
